version: '3.8'
services:
  nuxt-chess:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env

    depends_on:
      - supabase-db  # if using local Supabase

  supabase-db:
    image: supabase/postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: