export const NEW_GAME = 'NEW_GAME';
export const MOVE_PIECE = 'MOVE_PIECE';
export const CAPTURE_PIECE = 'CAPTURE_PIECE';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const UPDATE_TURN = 'UPDATE_TURN';
export const UPDATE_TURN_COUNT = 'UPDATE_TURN_COUNT';
export const UPDATE_GAME_HISTORY = 'UPDATE_GAME_HISTORY';
export const UPDATE_CURRENT_FEN = 'UPDATE_CURRENT_FEN';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const UPDATE_SELECTED_SQUARE = 'UPDATE_SELECTED_SQUARE';
export const PROMOTE_PAWN = 'PROMOTE_PAWN';

const ACTIONS = { NEW_GAME, MOVE_PIECE, CAPTURE_PIECE, UPDATE_GAME_STATUS, UPDATE_TURN, UPDATE_TURN_COUNT, UPDATE_GAME_HISTORY, UPDATE_CURRENT_FEN, UPDATE_POSITION, UPDATE_SELECTED_SQUARE, PROMOTE_PAWN };
export default ACTIONS;
